// <auto-generated />
using System;
using CalificacionesAlumnosMVCReact.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalificacionesAlumnosMVCReact.Migrations
{
    [DbContext(typeof(CalificacionesAlumnosContext))]
    [Migration("20230712062855_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("CalificacionesAlumnosMVCReact.Models.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Creditos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Curso");
                });

            modelBuilder.Entity("CalificacionesAlumnosMVCReact.Models.Estudiante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellidos")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Calificacion")
                        .HasColumnType("REAL");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Estudiante");
                });

            modelBuilder.Entity("CalificacionesAlumnosMVCReact.Models.EstudianteCurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Calificacion")
                        .HasColumnType("REAL");

                    b.Property<int?>("CursoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EstudianteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.HasIndex("EstudianteId");

                    b.ToTable("EstudianteCurso");
                });

            modelBuilder.Entity("CalificacionesAlumnosMVCReact.Models.EstudianteCurso", b =>
                {
                    b.HasOne("CalificacionesAlumnosMVCReact.Models.Curso", "Curso")
                        .WithMany("EstudiantesCursos")
                        .HasForeignKey("CursoId");

                    b.HasOne("CalificacionesAlumnosMVCReact.Models.Estudiante", "Estudiante")
                        .WithMany("EstudiantesCursos")
                        .HasForeignKey("EstudianteId");

                    b.Navigation("Curso");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("CalificacionesAlumnosMVCReact.Models.Curso", b =>
                {
                    b.Navigation("EstudiantesCursos");
                });

            modelBuilder.Entity("CalificacionesAlumnosMVCReact.Models.Estudiante", b =>
                {
                    b.Navigation("EstudiantesCursos");
                });
#pragma warning restore 612, 618
        }
    }
}
